name = "StenoGraphs"
uuid = "78862bba-adae-4a83-bb4d-33c106177f81"
version = "0.4.4"
authors = ["Aaron Peikert <aaron.peikert@posteo.de> and contributors"]

[weakdeps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DataFrames = "1"
Tables = "1"
julia = "1.9"

[extensions]
StenoGraphsDataFramesExt = ["DataFrames", "Tables"]
